// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	common "github.com/ebanfa/skeleton/pkg/common"
	mock "github.com/stretchr/testify/mock"
)

// EventBusInterface is an autogenerated mock type for the EventBusInterface type
type EventBusInterface struct {
	mock.Mock
}

// HasCallback provides a mock function with given fields: topic
func (_m *EventBusInterface) HasCallback(topic string) bool {
	ret := _m.Called(topic)

	if len(ret) == 0 {
		panic("no return value specified for HasCallback")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(topic)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Publish provides a mock function with given fields: event
func (_m *EventBusInterface) Publish(event common.Event) {
	_m.Called(event)
}

// Subscribe provides a mock function with given fields: params
func (_m *EventBusInterface) Subscribe(params common.BusSubscriptionParams) error {
	ret := _m.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(common.BusSubscriptionParams) error); ok {
		r0 = rf(params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SubscribeAsync provides a mock function with given fields: params, transactional
func (_m *EventBusInterface) SubscribeAsync(params common.BusSubscriptionParams, transactional bool) error {
	ret := _m.Called(params, transactional)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeAsync")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(common.BusSubscriptionParams, bool) error); ok {
		r0 = rf(params, transactional)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SubscribeOnce provides a mock function with given fields: params
func (_m *EventBusInterface) SubscribeOnce(params common.BusSubscriptionParams) error {
	ret := _m.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeOnce")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(common.BusSubscriptionParams) error); ok {
		r0 = rf(params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SubscribeOnceAsync provides a mock function with given fields: params
func (_m *EventBusInterface) SubscribeOnceAsync(params common.BusSubscriptionParams) error {
	ret := _m.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeOnceAsync")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(common.BusSubscriptionParams) error); ok {
		r0 = rf(params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Unsubscribe provides a mock function with given fields: params
func (_m *EventBusInterface) Unsubscribe(params common.BusSubscriptionParams) error {
	ret := _m.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for Unsubscribe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(common.BusSubscriptionParams) error); ok {
		r0 = rf(params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WaitAsync provides a mock function with given fields:
func (_m *EventBusInterface) WaitAsync() {
	_m.Called()
}

// NewEventBusInterface creates a new instance of EventBusInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventBusInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventBusInterface {
	mock := &EventBusInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
