// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	common "github.com/ebanfa/skeleton/pkg/common"
	mock "github.com/stretchr/testify/mock"
)

// LoggerInterface is an autogenerated mock type for the LoggerInterface type
type LoggerInterface struct {
	mock.Mock
}

// Log provides a mock function with given fields: level, args
func (_m *LoggerInterface) Log(level common.Level, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, level)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Logf provides a mock function with given fields: level, format, args
func (_m *LoggerInterface) Logf(level common.Level, format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, level, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// NewLoggerInterface creates a new instance of LoggerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoggerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *LoggerInterface {
	mock := &LoggerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
