// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ReadOnlyDatabase is an autogenerated mock type for the ReadOnlyDatabase type
type ReadOnlyDatabase struct {
	mock.Mock
}

// AvailableVersions provides a mock function with given fields:
func (_m *ReadOnlyDatabase) AvailableVersions() []int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AvailableVersions")
	}

	var r0 []int
	if rf, ok := ret.Get(0).(func() []int); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}

	return r0
}

// Get provides a mock function with given fields: key
func (_m *ReadOnlyDatabase) Get(key []byte) ([]byte, error) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) ([]byte, error)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Has provides a mock function with given fields: key
func (_m *ReadOnlyDatabase) Has(key []byte) (bool, error) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Has")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (bool, error)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func([]byte) bool); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Hash provides a mock function with given fields:
func (_m *ReadOnlyDatabase) Hash() []byte {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 []byte
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	return r0
}

// IsEmpty provides a mock function with given fields:
func (_m *ReadOnlyDatabase) IsEmpty() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsEmpty")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Iterate provides a mock function with given fields: fn
func (_m *ReadOnlyDatabase) Iterate(fn func([]byte, []byte) bool) error {
	ret := _m.Called(fn)

	if len(ret) == 0 {
		panic("no return value specified for Iterate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(func([]byte, []byte) bool) error); ok {
		r0 = rf(fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IterateRange provides a mock function with given fields: start, end, ascending, fn
func (_m *ReadOnlyDatabase) IterateRange(start []byte, end []byte, ascending bool, fn func([]byte, []byte) bool) error {
	ret := _m.Called(start, end, ascending, fn)

	if len(ret) == 0 {
		panic("no return value specified for IterateRange")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte, []byte, bool, func([]byte, []byte) bool) error); ok {
		r0 = rf(start, end, ascending, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// String provides a mock function with given fields:
func (_m *ReadOnlyDatabase) String() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Version provides a mock function with given fields:
func (_m *ReadOnlyDatabase) Version() int64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Version")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// WorkingHash provides a mock function with given fields:
func (_m *ReadOnlyDatabase) WorkingHash() []byte {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for WorkingHash")
	}

	var r0 []byte
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	return r0
}

// WorkingVersion provides a mock function with given fields:
func (_m *ReadOnlyDatabase) WorkingVersion() int64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for WorkingVersion")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// NewReadOnlyDatabase creates a new instance of ReadOnlyDatabase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReadOnlyDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReadOnlyDatabase {
	mock := &ReadOnlyDatabase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
