// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	common "github.com/ebanfa/skeleton/pkg/common"
	mock "github.com/stretchr/testify/mock"

	system "github.com/ebanfa/skeleton/pkg/system"
)

// SystemComponentInterface is an autogenerated mock type for the SystemComponentInterface type
type SystemComponentInterface struct {
	mock.Mock
}

// Description provides a mock function with given fields:
func (_m *SystemComponentInterface) Description() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Description")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ID provides a mock function with given fields:
func (_m *SystemComponentInterface) ID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Initialize provides a mock function with given fields: ctx, _a1
func (_m *SystemComponentInterface) Initialize(ctx *common.Context, _a1 system.SystemInterface) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Initialize")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*common.Context, system.SystemInterface) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Name provides a mock function with given fields:
func (_m *SystemComponentInterface) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Type provides a mock function with given fields:
func (_m *SystemComponentInterface) Type() system.ComponentType {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 system.ComponentType
	if rf, ok := ret.Get(0).(func() system.ComponentType); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(system.ComponentType)
	}

	return r0
}

// NewSystemComponentInterface creates a new instance of SystemComponentInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSystemComponentInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *SystemComponentInterface {
	mock := &SystemComponentInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
